---
- name: install redmine packages
  with_items: "{{ redmine_packages }}"
  package:
    name: "{{ item.name }}"
    state: latest
  notify:
    - restart redmine

- name: setup redmine template
  template:
    src: redmine.j2
    dest: /etc/rc.conf.d/redmine
    owner: root
    group: wheel
  notify:
    - restart redmine

- name: setup redmine service
  template:
    src: redmine.rd.j2
    dest: /usr/local/etc/rc.d/redmine
    owner: root
    group: wheel
  notify:
    - restart redmine

- name: setup database template
  template:
    src: "database.yml.j2"
    dest: "/usr/local/www/redmine/config/database.yml"
    owner: "root"
    group: "wheel"
    mode: 0644
  notify:
    - restart redmine

- name: generate secret token
  shell:
    chdir: /usr/local/www/redmine
    cmd: bundle exec rake generate_secret_token

- name: migrate database
  shell:
    chdir: /usr/local/www/redmine
    cmd: env RAILS_ENV=production bundle exec rake db:migrate

- name: load default data
  shell:
    chdir: /usr/local/www/redmine
    cmd: env RAILS_ENV=production REDMINE_LANG=en bundle exec rake redmine:load_default_data
