---
- name: restart redmine
  service:
    name: redmine
    state: restarted

- name: generate secret token
  shell: bundle exec rake generate_secret_token
  args:
    chdir: /usr/local/www/redmine

- name: prepare DB
  shell: RAILS_ENV=production bundle exec rake db:migrate
  args:
    chdir: /usr/local/www/redmine

- name: add initial DB data
  shell: RAILS_ENV=production REDMINE_LANG=en bundle exec rake redmine:load_default_data
  args:
    chdir: /usr/local/www/redmine
