---
- name: install packages
  with_items: "{{ redmine_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: configure database
  template:
    src: database.yml.j2
    dest: /usr/local/www/redmine/config/database.yml
