---
- name: setup /etc/hosts on localhost
  become: yes
  lineinfile:
    regexp: '^10\..*\..*\..* {{ domain }}'
    dest: /etc/hosts
    line: "{{ hostvars['web'].ansible_all_ipv4_addresses[0] }} {{ domain }}"
    state: present
