---
- name: setup /etc/hosts
  lineinfile:
    regexp: '^10\..*\..*\..* redmine$'
    dest: /etc/hosts
    line: "{{ hostvars['redmine'].ansible_all_ipv4_addresses[0] }} redmine"
    state: present

- name: configure nginx for redmine
  template:
    src: nginx-redmine.conf.j2
    dest: /usr/local/etc/nginx/conf.d/redmine.conf
  notify:
    - restart nginx
